### PR TITLE
fix link

### LINKED ISSUE #29: Broken link in As Seen In on homepage
Just a quick note to say the Refugees Deeply link, under the As Seen In section on the homepage, has a broken link.

:+1:

### PR DESCRIPTION
**Pull request by kkarimi**
fixes #29

### CODE REVIEW

File: src/components/AsSeen.js [hunk 1]
```diff
@@ -30,7 +30,7 @@ export const AsSeen = () => (
           </Link>
       </div>
       <div className="col-sm-3">
-          <Link href="https://www.newsdeeply.com/refugees/articles/2016/10/19/welcome-to-londons-refugee-coding-school"
+          <Link to="https://www.newsdeeply.com/refugees/articles/2016/10/19/welcome-to-londons-refugee-coding-school"
             to="_blank"
```
Comment (NateWr) [inline src/components/AsSeen.js]: Looking at other links, the `to="_blank"` should maybe be `target="_blank"`? :+1:

Comment (kkarimi) [inline src/components/AsSeen.js]: good catch
